apiVersion: apps/v1
kind: Deployment   
metadata:
  name: flask-app  
  labels:
    app: flask-app
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: flask-app
  template:     
    metadata:
      labels:
        app: flask-app
    spec:
      containers:  
      - name: flask-app1
        image: docker.io/gauravagnihotri25/minikube:micro-1
        ports:
        - containerPort: 5000
      - name: flask-app2
        image: docker.io/gauravagnihotri25/minikube:micro-2
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service  
metadata:
  name: flask-app   
  labels:
    app: flask-app   
spec:
  ports:
    - port: 5000
      targetPort: 5000  
  selector:
    app: flask-app
  type: LoadBalancer  
